"""create clinical_notes and patient_files

Revision ID: 58672ac73354
Revises: f9b8fa969bea
Create Date: 2026-10-09 22:58:43.301818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58672ac73354'
down_revision: Union[str, Sequence[str], None] = 'f9b8fa969bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'clinical_notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('doctor_id', sa.Integer(), nullable=False),
        sa.Column('appointment_id', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('amends_note_id', sa.Integer(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['amends_note_id'], ['clinical_notes.id'],
        ),
        sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id']),
        sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id']),
        sa.ForeignKeyConstraint(['patient_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_clinical_notes_amends_note_id'),
        'clinical_notes',
        ['amends_note_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinical_notes_appointment_id'),
        'clinical_notes',
        ['appointment_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinical_notes_doctor_id'),
        'clinical_notes',
        ['doctor_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinical_notes_id'),
        'clinical_notes',
        ['id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinical_notes_patient_id'),
        'clinical_notes',
        ['patient_id'],
        unique=False,
    )

    op.create_table(
        'patient_files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('sha256', sa.String(length=64), nullable=False),
        sa.Column('storage_path', sa.String(length=500), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['patient_id'], ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['uploaded_by_user_id'], ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_patient_files_id'),
        'patient_files',
        ['id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_files_patient_id'),
        'patient_files',
        ['patient_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_files_uploaded_by_user_id'),
        'patient_files',
        ['uploaded_by_user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_patient_files_uploaded_by_user_id'),
        table_name='patient_files',
    )
    op.drop_index(
        op.f('ix_patient_files_patient_id'),
        table_name='patient_files',
    )
    op.drop_index(
        op.f('ix_patient_files_id'),
        table_name='patient_files',
    )
    op.drop_table('patient_files')

    op.drop_index(
        op.f('ix_clinical_notes_patient_id'),
        table_name='clinical_notes',
    )
    op.drop_index(
        op.f('ix_clinical_notes_id'),
        table_name='clinical_notes',
    )
    op.drop_index(
        op.f('ix_clinical_notes_doctor_id'),
        table_name='clinical_notes',
    )
    op.create_index(
        op.f('ix_clinical_notes_appointment_id'),
        table_name='clinical_notes',
    )
    op.drop_index(
        op.f('ix_clinical_notes_amends_note_id'),
        table_name='clinical_notes',
    )
    op.drop_table('clinical_notes')
    # ### end Alembic commands ###